Repository sportheroes/bk-mocha-suite, pull requests merged in 2018-03, with the labels that each got.

#1 ✅ [ADD] (core) Add stubContext method to fast stub sonic context
  app.js
Labels: enhancement

#2 ✅ [ADD] (stubContext) Added support for new context methods
  app.js
Labels: Ready For Review, Size Small (< 100 lines)

#4 ✅ [ADD] Peer dependencies
  package-lock.json
  package.json
Labels: Ready For Review, Size Small (< 100 lines)

#6 ✅ [ADD] Add clone to stubContext
  app.js
Labels: Bug, Ready For Review, Size Small (< 100 lines)
